services:
  # Backend Service
  - type: web
    name: schedula-backend
    env: node
    buildCommand: cd apps/backend && npm install && tsc -p tsconfig.build.json
    startCommand: cd apps/backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

  # Frontend Service
  - type: web
    name: schedula-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npx nx build frontend --configuration=production
    startCommand: npx nx serve frontend --prod
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables your frontend needs here 