services:
  # Backend Service
  - type: web
    name: schedula-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables your backend needs here

  # Frontend Service
  - type: web
    name: schedula-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npx nx build frontend --configuration=production
    startCommand: npx nx serve frontend --prod
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables your frontend needs here 